### ISSUE TITLE
Rename instances in the Navigator feature

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1873] opened 2023-06-28 17:36 UTC
Naming your instances is an essential way to keep a project organized. Currently it's only possible to change the instance name in the Settings panel but there needs to be a faster, easier way.

The design for the Navigator items component already has a variant for renaming:
<img width="459" alt="Screenshot 2023-06-28 at 10 29 56 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/e9b9cde5-2bfa-4ecb-a464-5ea40d7a0c4c">
https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=8%3A1872&mode=design&t=vbowmO17y48m75hM-1

A double-click on the text area of the Navigator Item should initiate editing. (Reference Figma Layers for ideal behavior).

Ideally there would be a keyboard shortcut for changing the instance name of the current selection. In Figma it's `CMD/CTRL+R` Does that work for us?

**Comment by kof** [comment] 2023-06-28 17:39
duplicate of https://github.com/webstudio-is/webstudio-builder/issues/222 please merge the info and close this one

**Closed** 2023-06-28 17:54 UTC
Labels: type:enhancement, area:builder, prio:1
