### ISSUE TITLE
States that allow CSS pseudo-states (hover, focus) and custom states

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#83] opened 2022-06-24 17:13 UTC
Users will need a way to control CSS user action pseudo-classes, called "states" in Webflow. The big ones are **hover**, which provides some interactivity prior to our own "interactions" feature, and **focus** which is important for keyboard navigation and accessibility.

Webflow CSS states menu:
<img width="236" alt="Screen Shot 2022-06-24 at 9 59 49 AM" src="https://user-images.githubusercontent.com/86495896/175608103-031275c1-0aec-4f71-add1-2fe4ae1158e8.png">

In Webflow, selecting a state from the above menu will "refresh" the style panel. Users can then make style changes and those changes will only show when the state is activated. So changing a text color while the "hover" is active will result in the text color of that element changing when hovered.

We need a version of this that fits with our token system.

**Comment by taylornowotny** [comment] 2022-06-24 17:17
It may require a separate issue, but we should also have a way to control transitions. https://www.w3schools.com/css/css3_transitions.asp

The way Webflow handles this is very simple. Just a GUI to control the code. We could improve on this I'm sure.

One thing we will need to make this work is an easing manager.

**Comment by kof** [comment] 2022-06-24 17:33
looks like a duplicate of https://github.com/webstudio-is/webstudio-designer/issues/73 ? Lets merge them together and close one?

**Comment by kof** [comment] 2022-06-24 18:19
Additionally, the same UI could be used to define any states, so that to the user there is no difference if those are CSS native once or not.

This needs research and a design proposal.

**Comment by taylornowotny** [comment] 2022-06-27 20:47
Another state that I use a lot is "Current"

Common use case: Navigation links change color when user is on the linked page.

**Comment by taylornowotny** [comment] 2022-06-29 14:30
Ok. The reason I grouped them is because they work the same in Webflow. I
have no clue what’s going on under the hood, but styling the ‘current’
version of a link and styling the ‘hover’ state follow the same process.
From the perspective of a user it’s really easy in Webflow.

Should we come up with a UX proposal for how this could work in Webstudio
first and then revisit the issue?

**Comment by okonet** [comment] 2022-06-29 16:40
As I said, you can assume that some components will have "states" defined in them so the designer UI will know about them. There is nothing that should block you from making a UX proposal from my POV. Let me know what information is still missing to make a proposal.

**Comment by okonet** [comment] 2022-06-29 16:42
Not sure what you mean by class system since "states" are pseudo-states. We also will use same pseudo-classes under the hood.

**Comment by taylornowotny** [comment] 2022-06-29 16:49
<img width="239" alt="Screen Shot 2022-06-29 at 9 44 23 AM" src="https://user-images.githubusercontent.com/86495896/176491230-a3fb470e-3426-47b9-bbba-848675441bd6.png">
<img width="239" alt="Screen Shot 2022-06-29 at 9 45 06 AM" src="https://user-images.githubusercontent.com/86495896/176491315-47e0076b-4569-4447-9c98-892766a9a03b.png">

This is what I'm talking about. In the Webflow UI these are called "states" and they are managed as part of their class UI. We will not have a class UI like this, we will have user components instead.

So first we need to figure out how our component UI will work, and then I can figure out how to manage "states" or whatever we call them.

Components are priority 1 and this issue is priority 2

**Comment by kof** [comment] 2023-02-16 00:33
Closing, has a separate issue

**Closed by kof** 2023-02-16 00:33 UTC
Labels: area:styles, type:user story, complexity:high, prio:1
