### ISSUE TITLE
Remove preset colors and use CSS default

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1243] opened 2023-03-14 22:48 UTC
There are a couple of issues with the colors in the Typography section and the Backgrounds section.

- [ ] Default text color is incorrect. The CSS default is used here, which is "Black". We do not show a preset label for CSS defaults.

Prod: 
<img width="228" alt="Screenshot 2023-03-14 at 3 43 45 PM" src="https://user-images.githubusercontent.com/86495896/225158584-13eb15fc-abb2-4965-b81e-0f700c2dc063.png">
Design: 
<img width="371" alt="Screenshot 2023-03-14 at 3 44 54 PM" src="https://user-images.githubusercontent.com/86495896/225158670-f717811a-edfb-4418-b377-d401296da1e3.png">

- [ ] Default background color is incorrect. We do not need a white preset for the background. The CSS default is transparent.

Prod: 
<img width="239" alt="Screenshot 2023-03-14 at 3 48 32 PM" src="https://user-images.githubusercontent.com/86495896/225159159-06ded16a-e4aa-443e-82c8-d30eace66549.png">
Design: 
<img width="571" alt="Screenshot 2023-03-14 at 3 47 50 PM" src="https://user-images.githubusercontent.com/86495896/225159053-7d1c660c-86c7-450d-a74a-fcdb83364dc2.png">

**Comment by kof** [comment] 2023-03-14 23:02
@TrySound is this basically a duplicate of https://github.com/webstudio-is/webstudio-builder/issues/1067 ?

**Comment by taylornowotny** [comment] 2023-03-14 23:20
Not a duplicate but it's related

**Closed** 2023-04-21 04:59 UTC
Labels: type:bug, complexity:low, area:builder, prio:1
